notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
    on_success: [always|never|change] # default: change
    on_failure: [always|never|change] # default: always

language: scala
scala:
  - 2.11.0
jdk:
  - oraclejdk7
notifications:
    email:
      - recipients: lino+travis@lino.io
    on_success: always
